### ISSUE TITLE
name 'gid' is not defined

### ISSUE THREAD

**Issue by beantowel** [bill317996/Melody-extraction-with-melodic-segnet#2]
when using -gpu option, the predict_on_audio.py code would encounter NameError:
```
File "<basedir>/Melody-extraction-with-melodic-segnet/MSnet/MelodyExtraction.py", line 56, in MeExt
    Net.load_state_dict(torch.load(model_path, map_location={'cuda:2':'cuda:{}'.format(gid)}))
NameError: name 'gid' is not defined
```

**Comment by beantowel** [comment]
maybe the `map_location` should be `lambda storage, loc: storage.cuda()` ?

**Comment by 520dingyuxin** [comment]
I have the same problem，When I run the evaluation.py code.

**Comment by bill317996** [comment]
Fix this bug in predict_on_audio.py, evaluation.py and MSnet/MelodyExtraction.py

`est_arr = MeExt(filepath, model_type=model_type, model_path=model_path, GPU=True, mode=mode, gid=gpu_index)`

It should be able to run now.
